{{- if and .Values.api.enabled .Values.api.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cubeStack.api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "cubeStack.componentLabels" (dict "ctx" . "component" "api") | nindent 4 }}
  {{- include "cubeStack.maybeAnnotations" . | nindent 2 }}
spec:
  {{- if .Values.api.pdb.minAvailable }}
  minAvailable: {{ .Values.api.pdb.minAvailable }}
  {{- else if .Values.api.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.api.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels: {{- include "cubeStack.componentSelectorLabels" (dict "ctx" . "component" "api") | nindent 6 }}
{{- end }}
